### PR TITLE
after adding login and signup pages

### PR DESCRIPTION
**Pull request by rashed-08**

### CODE REVIEW

**Review by mahbubcseju — COMMENTED** [review]
No view function for login or logout!

**Comment by rashed-08** [comment]
There is no navbar, just login and signup page. So an user come to page mean, not able to login.

**Comment by mahbubcseju** [comment]
I added login and logout mechanism without any kind of confirmation. U may add the css now and let me know after adding.

**Comment by rashed-08** [comment]
I have added navbar and redesign as well.

**Review by mahbubcseju — COMMENTED** [review]
Have you checked locally ? I think you should only overwrite my login or signup pages

**Comment by rashed-08** [comment]
Yes, I do. 
In base design, just I have changed the code, but remain the design. If you are not satisfied, then I'll revert it.

**Pull request closed without merging**
